import type { Metadata } from "next";
import { Baloo_Da_2, Hind_Siliguri } from "next/font/google";
import "./globals.css";


const hind = Baloo_Da_2({
  weight:["400","500","600","700","800"],
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Dakbaksho",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hind.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
